openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /task_search:
    post:
      summary: Отправить данные
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                kr_name:
                  type: string
                  description: Данные из формы
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tasks"
  /task2_create:
    post:
        summary: Отправить данные
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  kr_name:
                    type: string
                    description: Данные из формы
                  name:
                    type: string
                    description: Данные из формы
                  kategor:
                    type: string
                    description: Данные из формы
                    enum:
                      - К
                      - КТ
                      - ПНд
                  tip:
                    type: string
                    description: Данные из формы
                    enum:
                      - локальная
                      - корпоративная
        responses:
          '200':
            description: Task created successfully
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/tasks"
  /task2_search:
       post:
        summary: Отправить данные
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  kr_name:
                    type: string
                    description: Данные из формы
        responses:
          '200':
            description: Task created successfully
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/task"
  
  /task3_search:
      post:
        summary: Отправить данные
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Данные из формы
        responses:
          '200':
            description: Task created successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    info:
                      type: string
                      description: Данные из формы
components:
  schemas:
    task:
      type: object
      required:
        - id
        - kr_name
        - name
        - kategor
        - tip
      properties:
        id:
          type: integer
          description: Уникальный идентификатор
        kr_name:
          type: string
          description: Краткое наименование
        name:
          type: string
          description: Полное наименование
        kategor:
          type: string
          enum:
            - К
            - КТ
            - ПНд
        tip:
          type: string
          enum:
          - локальная
          - корпоративная
        naznach:
          type: string
        data_vvoda:
          type: string
        zakazchik:
          type: string
        data_ib:
          type: string
        primech:
          type: string
    tasks:
      type: array
      items:
        $ref: "#/components/schemas/task"