openapi: 3.0.0
info:
  title: Task API
  version: 1.0
  description: API for managing tasks
paths:
  /task_create:
    post:
      summary: Create a new task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: Уникальный идентификатор
                kr_name:
                  type: string
                  description: Краткое наименование
                name:
                  type: string
                  description: Полное наименование
                kategor:
                  type: string
                  description: Категория
                tip:
                  type: string
                  description: Тип
                naznach:
                  type: string
                  description: Назначение
                data_vvoda:
                  type: null
                  description: Дата ввода
                zakazchik:
                  type: null
                  description: Заказчик
                data_ib:
                  type: null
                  description: Дата последнего проведения ИБ ИС
                primech:
                  type: null
                  description: Примечание
              required:
                - id
                - kr_name
                - name
                - kategor
                - tip
                - naznach
                - data_vvoda
                - zakazchik
                - data_ib
                - primech
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  kr_name:
                    type: string
                    name:
                      type: string
                    kategor:
                      type: string
                    tip:
                      type: string
                    naznach:
                      type: string
                    data_vvoda:
                      type: null
                    zakazchik:
                      type: null
                    data_ib:
                      type: null
                    primech:
                      type: null

